//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainClientSystem {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Printer : global::System.Configuration.ApplicationSettingsBase {
        
        private static Printer defaultInstance = ((Printer)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Printer())));
        
        public static Printer Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DefaultPrinterName {
            get {
                return ((string)(this["DefaultPrinterName"]));
            }
            set {
                this["DefaultPrinterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Printing.PaperSize PaperSize {
            get {
                return ((global::System.Drawing.Printing.PaperSize)(this["PaperSize"]));
            }
            set {
                this["PaperSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public float XPosition {
            get {
                return ((float)(this["XPosition"]));
            }
            set {
                this["XPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public float YPosition {
            get {
                return ((float)(this["YPosition"]));
            }
            set {
                this["YPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Landscape {
            get {
                return ((bool)(this["Landscape"]));
            }
            set {
                this["Landscape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Font FontToPrint {
            get {
                return ((global::System.Drawing.Font)(this["FontToPrint"]));
            }
            set {
                this["FontToPrint"] = value;
            }
        }
    }
}
