//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 计算机快速设置.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("计算机快速设置.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap _NETLogo {
            get {
                object obj = ResourceManager.GetObject("_NETLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 计算机名称不能为空！ 的本地化字符串。
        /// </summary>
        internal static string ErrorString1 {
            get {
                return ResourceManager.GetString("ErrorString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算机名称修改失败！ 的本地化字符串。
        /// </summary>
        internal static string ErrorString2 {
            get {
                return ResourceManager.GetString("ErrorString2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 域名称修改失败！ 的本地化字符串。
        /// </summary>
        internal static string ErrorString3 {
            get {
                return ResourceManager.GetString("ErrorString3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入域时出错！ 的本地化字符串。
        /// </summary>
        internal static string ErrorString4 {
            get {
                return ResourceManager.GetString("ErrorString4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建用户失败！ 的本地化字符串。
        /// </summary>
        internal static string ErrorString5 {
            get {
                return ResourceManager.GetString("ErrorString5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入工作组时出错！ 的本地化字符串。
        /// </summary>
        internal static string ErrorString6 {
            get {
                return ResourceManager.GetString("ErrorString6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同步到域时出错！ 的本地化字符串。
        /// </summary>
        internal static string ErrorString7 {
            get {
                return ResourceManager.GetString("ErrorString7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知错误！ 的本地化字符串。
        /// </summary>
        internal static string ErrorStringUnknown {
            get {
                return ResourceManager.GetString("ErrorStringUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本文档（*.txt）|*.txt|配置文件（*.ini）|*.ini 的本地化字符串。
        /// </summary>
        internal static string ExtFilter {
            get {
                return ResourceManager.GetString("ExtFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LDAP:// 的本地化字符串。
        /// </summary>
        internal static string LDAPProtocol {
            get {
                return ResourceManager.GetString("LDAPProtocol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap more {
            get {
                object obj = ResourceManager.GetObject("more", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 计算机名称没有做任何修改！ 的本地化字符串。
        /// </summary>
        internal static string PromptString1 {
            get {
                return ResourceManager.GetString("PromptString1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap WindowsLogo {
            get {
                object obj = ResourceManager.GetObject("WindowsLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 WinNT:// 的本地化字符串。
        /// </summary>
        internal static string WinNTProtocol {
            get {
                return ResourceManager.GetString("WinNTProtocol", resourceCulture);
            }
        }
    }
}
